### ISSUE TITLE
README

### ISSUE THREAD

**Issue by jschenke488** [jays-homelab/cheesy-arena-lite#1]
If you are finding this repository, the purpose is to allow having a private fork of Cheesy Arena Lite. GitHub normally prevents private forks for security, which is a good thing, but the license of Cheesy Arena Lite prevents redistribution of modified versions. In order to use GitHub for our fork, we had to find a way to make it private. We found that GitHub Actions can do just that. First, you create a public fork of the original project in an organization and add a workflow file with the following content:
```yml
name: hehe

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

jobs:
  hehe:
    runs-on: ubuntu-latest
    if: github.repository == 'jays-homelab/cheesy-arena-lite-private-mirror'

    steps:
      - name: Run a multi-line script
        run: |
          git config --global user.name "Jay"
          git config --global user.email "jschenke488@lsr7.net"
          git clone --mirror https://github.com/jays-homelab/cheesy-arena-lite cheesy-arena-lite
          cd cheesy-arena-lite
          git remote remove origin
          git remote add origin https://jschenke488:${{ secrets.GIT_TOKEN }}@github.com/jays-homelab/crimson-arena
          git push -f --prune --all
          git push -f --prune --tag
```

The reason for it being named hehe is because that name is very unlikely to create a merge conflict once the public fork is synced. Afterwards, create a second empty repository that is private and add the same workflow to it. Make sure to replace the if condition in both repositories with the name of your private repository. Additionally, replace the username, email, and URLs with the the correct information. In the private repository, add a secret at https://github.com/user/repo/settings/secrets/actions named GIT_TOKEN containing a personal access token. Create a *classic* personal access token with the repo, workflow, and admin:org scopes at https://github.com/settings/tokens. Don't share this token! Enable private forking at https://github.com/organizations/ORG/settings/member_privileges where ORG is your organization name. You can now fork the private mirror to create your private fork.
